name: Deno

permissions:
  contents: write

on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.0

      - name: Run deno
        run: |
          deno run --allow-all script.ts ${{ secrets.N8N_URL }}