name: Deno

permissions:
  contents: write

on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.0

      - name: Run deno
        run: |
          deno run --allow-all script.ts ${{ secrets.N8N_URL }}

      - name: Commit changes to lastAnnouncedVersion.txt
        run: |
          git config --global user.email "13621351+liqtags@users.noreply.github.com"
          git config --global user.name "liqtags"
          git add lastAnnouncedVersion.txt
          git commit -m "Announcing version ${{ steps.deno.outputs.version }}"
          git push
